# ============================================================================
# s55: Regularized Logistic Regression on LIBSVM Datasets
# ============================================================================
#
# Solves constrained logistic regression via derivative-free projection:
#   min_{x ∈ [-C,C]^n}  (1/N) Σ log(1+exp(-bᵢ aᵢᵀx)) + (μ/2)||x||²
# by finding G(x) = ∇f(x) = 0 with box-constrained projection.
#
# Loads pre-converted CSV files from data/libsvm/ (generated by s20).
# Features are standardized (zero mean, unit variance) before solving.
#
# Usage:
#   cd jcode
#   julia --project=. scripts/s55_logreg.jl                     # full run
#   julia --project=. scripts/s55_logreg.jl --quick              # a1a.t + colon-cancer, 1 trial
#   julia --project=. scripts/s55_logreg.jl --resume             # skip completed rows
#   julia --project=. scripts/s55_logreg.jl --datasets=a1a.t,colon-cancer
#   julia --project=. scripts/s55_logreg.jl --methods=GCGPM,GMOPCGM
#   julia --project=. scripts/s55_logreg.jl --summary            # print summary and exit
#
# Output:
#   results/logreg/logreg_results.csv   — one row per (method, dataset, trial)
#   results/logs/logreg_TIMESTAMP.log   — console + log
# ============================================================================

include(joinpath(@__DIR__, "..", "src", "includes.jl"))
using CSV, DataFrames

# ── Configuration ────────────────────────────────────────────────────────────

const MU       = 0.1       # ℓ₂ regularization parameter
const C_BOX    = 10.0      # box constraint bound: Γ = [-C, C]^n
const EPS_LR   = 1e-11     # convergence tolerance
const MAXITER  = 5000      # maximum iterations
const N_TRIALS = 5         # independent random initial points per dataset
const RNG_SEED = 42

const ALL_DATASETS = [
    "a1a.t", "a2a.t", "a3a.t", "a4a.t", "a5a.t",
    "a6a.t", "a7a.t", "a8a.t", "a9a.t",
    "colon-cancer", "w1a.t", "w2a.t",
]

const ALL_METHODS = [
    ("GMOPCGM", GMOPCGMMethod()),
    ("GCGPM",   GCGPMMethod()),
    ("MOPCGM",  MOPCGMMethod()),
    ("CGPM",    CGPMMethod()),
    ("STTDFPM", STTDFPMMethod()),
]

const DATA_DIR = joinpath(JCODE_ROOT, "data", "libsvm")

# ── ARGS parsing ─────────────────────────────────────────────────────────────

quick_mode   = false
do_resume    = false
do_summary   = false
datasets_arg = String[]
methods_arg  = String[]

for a in ARGS
    if a == "--quick"
        global quick_mode = true
    elseif a == "--resume"
        global do_resume = true
    elseif a == "--summary"
        global do_summary = true
    elseif startswith(a, "--datasets=")
        global datasets_arg = split(a[length("--datasets=")+1:end], ",")
    elseif startswith(a, "--methods=")
        global methods_arg = split(a[length("--methods=")+1:end], ",")
    else
        @warn "Unknown argument: $a"
    end
end

# Resolve datasets
if quick_mode
    DATASETS_RUN = ["a1a.t", "colon-cancer"]
    N_TRIALS_RUN = 1
elseif !isempty(datasets_arg)
    DATASETS_RUN = String.(datasets_arg)
    N_TRIALS_RUN = N_TRIALS
else
    DATASETS_RUN = ALL_DATASETS
    N_TRIALS_RUN = N_TRIALS
end

# Resolve methods
if !isempty(methods_arg)
    mset = Set(String.(methods_arg))
    METHODS_RUN = filter(m -> m[1] in mset, ALL_METHODS)
else
    METHODS_RUN = ALL_METHODS
end

# ── Output setup ─────────────────────────────────────────────────────────────

results_dir = joinpath(JCODE_ROOT, "results", "logreg")
mkpath(results_dir)
raw_csv = joinpath(results_dir, "logreg_results.csv")

const CSV_HEADER = ["method", "dataset", "trial", "n_features", "n_samples",
                    "converged", "iterations", "f_evals", "cpu_time", "residual",
                    "accuracy"]

# ── Summary mode ─────────────────────────────────────────────────────────────

if do_summary
    if !isfile(raw_csv)
        println("No results file found: $raw_csv")
        exit(1)
    end
    df = CSV.read(raw_csv, DataFrame)
    println("=" ^ 80)
    println("Logistic Regression — Summary (from $raw_csv)")
    println("  Total rows: $(nrow(df))")
    println("-" ^ 80)
    @printf("  %-10s %6s %8s %8s %10s %12s %8s\n",
            "Method", "Conv%", "med_IT", "med_FE", "med_CPU", "med_resid", "med_Acc")
    println("-" ^ 80)
    for (mname, _) in ALL_METHODS
        sub = filter(r -> r.method == mname, df)
        nrow(sub) == 0 && continue
        conv = filter(r -> r.converged, sub)
        pct = 100.0 * nrow(conv) / nrow(sub)
        if nrow(conv) > 0
            med_acc = median(conv.accuracy)
            @printf("  %-10s %5.1f%% %8.0f %8.0f %10.4f %12.2e %7.2f%%\n",
                    mname, pct, median(conv.iterations), median(conv.f_evals),
                    median(conv.cpu_time), median(conv.residual), 100.0 * med_acc)
        else
            @printf("  %-10s %5.1f%% %8s %8s %10s %12s %8s\n",
                    mname, pct, "---", "---", "---", "---", "---")
        end
    end
    println("=" ^ 80)

    # Per-dataset breakdown
    println("\nPer-dataset convergence:")
    println("-" ^ 80)
    @printf("  %-15s", "Dataset")
    for (mname, _) in ALL_METHODS; @printf(" %10s", mname); end
    println()
    println("-" ^ 80)
    for ds in ALL_DATASETS
        dssub = filter(r -> r.dataset == ds, df)
        nrow(dssub) == 0 && continue
        @printf("  %-15s", ds)
        for (mname, _) in ALL_METHODS
            msub = filter(r -> r.method == mname, dssub)
            if nrow(msub) > 0
                conv = count(r -> r.converged, eachrow(msub))
                @printf(" %7d/%-2d", conv, nrow(msub))
            else
                @printf(" %10s", "---")
            end
        end
        println()
    end
    exit(0)
end

# ── Logging ──────────────────────────────────────────────────────────────────

logpath, tee, logfile = setup_logging("logreg")

println(tee, "=" ^ 80)
println(tee, "Logistic Regression: LIBSVM Datasets")
println(tee, "=" ^ 80)
@tprintf(tee, "  μ=%.2f, C=%.1f, ε=%.0e, maxiter=%d, trials=%d\n",
         MU, C_BOX, EPS_LR, MAXITER, N_TRIALS_RUN)
@tprintf(tee, "  datasets: %s\n", join(DATASETS_RUN, ", "))
@tprintf(tee, "  methods:  %s\n", join([m[1] for m in METHODS_RUN], ", "))
@tprintf(tee, "  quick=%s, resume=%s\n", quick_mode, do_resume)
println(tee, "-" ^ 80)

# ── Resume detection ─────────────────────────────────────────────────────────

completed = Set{NTuple{3,String}}()
if do_resume && isfile(raw_csv)
    for line in eachline(raw_csv)
        startswith(line, "method") && continue
        parts = split(line, ",")
        length(parts) >= 3 && push!(completed, (parts[1], parts[2], parts[3]))
    end
    @tprintf(tee, "Resume: %d rows already done\n", length(completed))
end

# ── CSV file ─────────────────────────────────────────────────────────────────

raw_io = open(raw_csv, do_resume && isfile(raw_csv) ? "a" : "w")
if !(do_resume && isfile(raw_csv) && filesize(raw_csv) > 0)
    println(raw_io, join(CSV_HEADER, ","))
    flush(raw_io)
end

# ── Progress bar ─────────────────────────────────────────────────────────────

total_solves = length(DATASETS_RUN) * N_TRIALS_RUN * length(METHODS_RUN)
n_done = Ref(0)
n_conv = Ref(0)
n_fail = Ref(0)
prog = Progress(total_solves; barlen=40, showspeed=true, desc="  LogReg: ")
cb = ProgressCallback(prog, "", MAXITER, n_done, total_solves, n_conv, n_fail)

# ── Main loop ────────────────────────────────────────────────────────────────

for ds_name in DATASETS_RUN
    csv_path = joinpath(DATA_DIR, "$(ds_name).csv")
    if !isfile(csv_path)
        println(tee.log, "  SKIP: $csv_path not found")
        for _ in 1:(N_TRIALS_RUN * length(METHODS_RUN))
            n_done[] += 1
            n_fail[] += 1
        end
        continue
    end

    # Load and normalize
    A, b = load_libsvm_csv(csv_path)
    normalize_features!(A)
    N_samples, n_features = size(A)
    prob, _ = make_logreg_problem(A, b; mu=MU, C=C_BOX)

    # Log dataset info to file only (not console — would break progress bar)
    @printf(tee.log, "\n  %s: N=%d, n=%d\n", ds_name, N_samples, n_features)

    for trial in 1:N_TRIALS_RUN
        rng = Random.Xoshiro(RNG_SEED + trial - 1)
        x0 = 4.0 .* (rand(rng, n_features) .- 0.5)  # x₀ ∈ [-2, 2]^n

        for (mname, method) in METHODS_RUN
            key = (mname, ds_name, string(trial))
            if key in completed
                n_done[] += 1
                ProgressMeter.update!(prog, n_done[];
                    showvalues=[(:done, "$(n_done[])/$(total_solves)"),
                                (:converged, n_conv[]), (:failed, n_fail[]),
                                (:current, "SKIP $mname $ds_name t=$trial")])
                continue
            end

            cb.label = "$mname $ds_name (N=$N_samples n=$n_features) t=$trial"
            result = try
                solve(method, prob, x0; eps=EPS_LR, maxiter=MAXITER, cb=cb,
                      stall_limit=typemax(Int))
            catch e
                _pcb_done!(cb, false)
                @printf(tee.log, "    ERROR: %s %s trial=%d: %s\n", mname, ds_name, trial, e)
                SolverResult(false, 0, 0, NaN, 0.0, x0)
            end

            # Classification accuracy
            acc = result.converged ? mean(sign.(A * result.x) .== b) : NaN

            @printf(raw_io, "%s,%s,%d,%d,%d,%s,%d,%d,%.6f,%.6e,%.6f\n",
                    mname, ds_name, trial, n_features, N_samples,
                    result.converged, result.iterations, result.f_evals,
                    result.cpu_time, result.residual, acc)
            flush(raw_io)
        end
    end
end

finish!(prog)
close(raw_io)

# ── Summary ──────────────────────────────────────────────────────────────────

println(tee, "\n" * "=" ^ 80)
println(tee, "Summary by method:")
println(tee, "-" ^ 80)

df = CSV.read(raw_csv, DataFrame)
@tprintf(tee, "  %-10s %6s %8s %8s %10s %12s %8s\n",
         "Method", "Conv%", "med_IT", "med_FE", "med_CPU", "med_resid", "med_Acc")
println(tee, "-" ^ 80)
for (mname, _) in ALL_METHODS
    sub = filter(r -> r.method == mname, df)
    nrow(sub) == 0 && continue
    conv = filter(r -> r.converged, sub)
    pct = 100.0 * nrow(conv) / nrow(sub)
    if nrow(conv) > 0
        med_acc = median(conv.accuracy)
        @tprintf(tee, "  %-10s %5.1f%% %8.0f %8.0f %10.4f %12.2e %7.2f%%\n",
                 mname, pct, median(conv.iterations), median(conv.f_evals),
                 median(conv.cpu_time), median(conv.residual), 100.0 * med_acc)
    else
        @tprintf(tee, "  %-10s %5.1f%% %8s %8s %10s %12s %8s\n",
                 mname, pct, "---", "---", "---", "---", "---")
    end
end

println(tee, "\nResults: $raw_csv")
teardown_logging(tee, logpath)
