# ============================================================================
# s75: Table Generation from benchmark data
# ============================================================================
#
# Generates:
#   Table A — Aggregate summary (per method)
#   Table P — Per-problem convergence counts
#   Table C — Pairwise wins matrix
#   Table D — Per-dimension summary
#   Table B — Full detailed results (content-only tables.tex)
#   Table E — Compressed-sensing summary
#   Table F — Logistic-regression summary
#
# Usage:
#   cd jcode
#   julia --project=. scripts/s75_tables.jl
# ============================================================================

include(joinpath(@__DIR__, "..", "src", "includes.jl"))
using CSV, DataFrames

const RESULTS_DIR = joinpath(JCODE_ROOT, "results", "benchmark")
const TABLES_DIR = joinpath(JCODE_ROOT, "results", "tables")
mkpath(TABLES_DIR)
const METHOD_ORDER = ["SOPP", "SDLP", "MOPCGM", "CGPM", "STTDFPM"]

format_median(x::Real) = isinteger(x) ? @sprintf("%.0f", x) : @sprintf("%.1f", x)

logpath, tee, logfile = setup_logging("tables")

# ── Load data ────────────────────────────────────────────────────────────────
raw_csv = joinpath(RESULTS_DIR, "raw.csv")
if !isfile(raw_csv)
    println(tee, "ERROR: raw.csv not found at $raw_csv")
    teardown_logging(tee, logpath)
    exit(1)
end

df = CSV.read(raw_csv, DataFrame)
available = intersect(METHOD_ORDER, unique(df.method))
@tprintf(tee, "Loaded %d rows, %d methods: %s\n", nrow(df), length(available), join(available, ", "))

# ═══════════════════════════════════════════════════════════════════════════════
# Table A: Aggregate summary
# ═══════════════════════════════════════════════════════════════════════════════

println(tee, "\n" * "=" ^ 75)
println(tee, "Table A: Aggregate Summary")
println(tee, "=" ^ 75)

table_a_rows = []
for m in available
    sub = filter(r -> r.method == m, df)
    conv = filter(r -> r.converged, sub)
    nt = nrow(sub); nc = nrow(conv)
    push!(table_a_rows, (
        method = m,
        total = nt,
        converged = nc,
        rate = round(100 * nc / nt; digits=1),
        med_IT = nc > 0 ? round(median(conv.iterations); digits=0) : NaN,
        med_FE = nc > 0 ? round(median(conv.f_evals); digits=0) : NaN,
        med_CPU = nc > 0 ? median(conv.cpu_time) : NaN,
    ))
end

@tprintf(tee, "%-10s %6s %6s %7s %8s %8s %10s\n",
         "Method", "Total", "Conv", "Rate%", "med_IT", "med_FE", "med_CPU")
println(tee, "-" ^ 65)
for r in table_a_rows
    @tprintf(tee, "%-10s %6d %6d %6.1f%% %8.0f %8.0f %10.4f\n",
             r.method, r.total, r.converged, r.rate, r.med_IT, r.med_FE, r.med_CPU)
end

# LaTeX output
table_a_tex = joinpath(TABLES_DIR, "table_A.tex")
open(table_a_tex, "w") do io
    println(io, "% Table A: Aggregate Summary (auto-generated by s75_tables.jl)")
    println(io, "\\begin{table}[ht]")
    println(io, "\\centering")
    println(io, "\\caption{Aggregate performance over all test problems, dimensions, and initial points.}\\label{tab:aggregate}")
    println(io, "\\begin{tabular}{lrrrrrr}")
    println(io, "\\toprule")
    println(io, "Method & Total & Conv & Rate (\\%) & med IT & med FE & med CPU (s) \\\\")
    println(io, "\\midrule")
    for r in table_a_rows
        @printf(io, "\\%s & %d & %d & %.1f & %.0f & %.0f & %.3f \\\\\n",
                r.method, r.total, r.converged, r.rate, r.med_IT, r.med_FE, r.med_CPU)
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "\\end{table}")
end
println(tee, "Saved: $table_a_tex")

# ═══════════════════════════════════════════════════════════════════════════════
# Table C: Pairwise wins matrix
# ═══════════════════════════════════════════════════════════════════════════════

println(tee, "\n" * "=" ^ 75)
println(tee, "Table C: Pairwise Wins (by iterations)")
println(tee, "=" ^ 75)

# For each instance, determine winner among converged methods
instances = unique(select(df, :problem, :n, :x0_label))
wins = Dict((m1, m2) => 0 for m1 in available, m2 in available if m1 != m2)
ties = Dict((m1, m2) => 0 for m1 in available, m2 in available if m1 != m2)

for inst in eachrow(instances)
    sub = filter(r -> r.problem == inst.problem && r.n == inst.n &&
                      r.x0_label == inst.x0_label && r.converged, df)
    nrow(sub) == 0 && continue
    for m1 in available, m2 in available
        m1 == m2 && continue
        r1 = filter(r -> r.method == m1, sub)
        r2 = filter(r -> r.method == m2, sub)
        (nrow(r1) == 0 || nrow(r2) == 0) && continue
        it1 = r1[1, :iterations]; it2 = r2[1, :iterations]
        if it1 < it2
            wins[(m1, m2)] += 1
        elseif it1 == it2
            ties[(m1, m2)] += 1
        end
    end
end

# Print: rows = method, cols = "vs method2: W/T/L"
@tprintf(tee, "%-10s", "")
for m in available
    @tprintf(tee, " %12s", m)
end
println(tee, "")
println(tee, "-" ^ (10 + 13 * length(available)))
for m1 in available
    @tprintf(tee, "%-10s", m1)
    for m2 in available
        if m1 == m2
            @tprintf(tee, " %12s", "---")
        else
            w = get(wins, (m1, m2), 0)
            t = get(ties, (m1, m2), 0)
            l = get(wins, (m2, m1), 0)
            @tprintf(tee, " %4d/%3d/%-3d", w, t, l)
        end
    end
    println(tee, "")
end

# LaTeX output
table_c_tex = joinpath(TABLES_DIR, "table_C.tex")
open(table_c_tex, "w") do io
    println(io, "% Table C: Pairwise wins/ties/losses (auto-generated by s75_tables.jl)")
    println(io, "\\begin{table}[ht]")
    println(io, "\\centering")
    println(io, "\\caption{Pairwise comparison (wins/ties/losses by iterations). Row method vs.\\ column method.}\\label{tab:wins}")
    println(io, "\\small")
    print(io, "\\begin{tabular}{l")
    for _ in available; print(io, "c"); end
    println(io, "}")
    println(io, "\\toprule")
    print(io, " ")
    for m in available; print(io, " & \\", m); end
    println(io, " \\\\")
    println(io, "\\midrule")
    for m1 in available
        print(io, "\\", m1)
        for m2 in available
            if m1 == m2
                print(io, " & ---")
            else
                w = get(wins, (m1, m2), 0)
                t = get(ties, (m1, m2), 0)
                l = get(wins, (m2, m1), 0)
                @printf(io, " & %d/%d/%d", w, t, l)
            end
        end
        println(io, " \\\\")
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "\\end{table}")
end
println(tee, "Saved: $table_c_tex")

# ═══════════════════════════════════════════════════════════════════════════════
# Table P: Per-problem convergence counts
# ═══════════════════════════════════════════════════════════════════════════════

println(tee, "\n" * "=" ^ 75)
println(tee, "Table P: Per-Problem Convergence Counts")
println(tee, "=" ^ 75)

internal_problem_ids = sort(unique(parse.(Int, replace.(String.(df.problem), "P" => ""))))
table_p_rows = []
for (paper_problem_number, internal_problem_id) in enumerate(internal_problem_ids)
    problem = string("P", internal_problem_id)
    counts = [count(r -> r.problem == problem && r.method == m && r.converged, eachrow(df))
              for m in available]
    push!(table_p_rows, (problem=paper_problem_number, counts=counts))
end

table_p_tex = joinpath(TABLES_DIR, "table_P.tex")
open(table_p_tex, "w") do io
    println(io, "% Table P: Per-problem convergence counts (auto-generated by s75_tables.jl)")
    println(io, "\\begin{table}[ht]")
    println(io, "\\centering")
    println(io, "\\caption{Converged instances out of 60 per problem and method.}\\label{tab:perproblem}")
    println(io, "\\small")
    print(io, "\\begin{tabular}{c")
    for _ in available; print(io, "c"); end
    println(io, "}")
    println(io, "\\toprule")
    print(io, "Problem")
    for m in available; print(io, " & \\" * m); end
    println(io, " \\\\")
    println(io, "\\midrule")
    for r in table_p_rows
        print(io, r.problem)
        for converged in r.counts; print(io, " & $converged"); end
        println(io, " \\\\")
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "\\end{table}")
end
println(tee, "Saved: $table_p_tex")

# ═══════════════════════════════════════════════════════════════════════════════
# Table D: Per-dimension summary
# ═══════════════════════════════════════════════════════════════════════════════

println(tee, "\n" * "=" ^ 75)
println(tee, "Table D: Per-Dimension Summary")
println(tee, "=" ^ 75)

dims = sort(unique(df.n))
table_d_rows = []

@tprintf(tee, "%-10s %8s %6s %7s %8s %8s %10s\n",
         "Method", "n", "Conv", "Rate%", "med_IT", "med_FE", "med_CPU")
println(tee, "-" ^ 70)

for m in available
    for d in dims
        sub = filter(r -> r.method == m && r.n == d, df)
        nrow(sub) == 0 && continue
        conv = filter(r -> r.converged, sub)
        nt = nrow(sub); nc = nrow(conv)
        row = (method=m, n=d, total=nt, converged=nc,
               rate=round(100nc/nt; digits=1),
               med_IT=nc>0 ? round(median(conv.iterations); digits=0) : NaN,
               med_FE=nc>0 ? round(median(conv.f_evals); digits=0) : NaN,
               med_CPU=nc>0 ? median(conv.cpu_time) : NaN)
        push!(table_d_rows, row)
        @tprintf(tee, "%-10s %8d %6d %6.1f%% %8.0f %8.0f %10.4f\n",
                 m, d, nc, row.rate, row.med_IT, row.med_FE, row.med_CPU)
    end
end

# LaTeX output
table_d_tex = joinpath(TABLES_DIR, "table_D.tex")
open(table_d_tex, "w") do io
    println(io, "% Table D: Per-Dimension Summary (auto-generated by s75_tables.jl)")
    println(io, "\\begin{table}[ht]")
    println(io, "\\centering")
    println(io, "\\caption{Per-dimension performance summary.}\\label{tab:perdim}")
    println(io, "\\small")
    println(io, "\\begin{tabular}{llrrrrr}")
    println(io, "\\toprule")
    println(io, "Method & \$n\$ & Conv & Rate (\\%) & med IT & med FE & med CPU (s) \\\\")
    println(io, "\\midrule")
    prev_method = ""
    for r in table_d_rows
        if r.method != prev_method && prev_method != ""
            println(io, "\\midrule")
        end
        @printf(io, "\\%s & %d & %d & %.1f & %.0f & %.0f & %.4f \\\\\n",
                r.method, r.n, r.converged, r.rate, r.med_IT, r.med_FE, r.med_CPU)
        prev_method = r.method
    end
    println(io, "\\bottomrule")
    println(io, "\\end{tabular}")
    println(io, "\\end{table}")
end
println(tee, "Saved: $table_d_tex")

# ═══════════════════════════════════════════════════════════════════════════════
# Table B: Full detailed results (content-only tables.tex)
# ═══════════════════════════════════════════════════════════════════════════════

println(tee, "\n" * "=" ^ 75)
println(tee, "Table B: Full Detailed Results (content only)")
println(tee, "=" ^ 75)

table_b_tex = joinpath(TABLES_DIR, "tables.tex")
open(table_b_tex, "w") do io
    println(io, "% Detailed numerical results (auto-generated content fragment)")
    println(io, "\\sisetup{exponent-mode=scientific, round-mode=places, round-precision=2}")
    println(io, "")

    # One longtable per dimension
    for d in dims
        df_dim = filter(r -> r.n == d, df)
        problems = sort(unique(df_dim.problem))

        println(io, "\\begin{longtable}{ll*{$(length(available))}{rrr}}")
        println(io, "\\caption{Results for \$n = $d\$. IT/FE/CPU for each method.}\\\\")
        println(io, "\\toprule")
        print(io, "Problem & \$x_0\$")
        for m in available
            print(io, " & \\multicolumn{3}{c}{\\$m}")
        end
        println(io, " \\\\")
        # Sub-header
        print(io, " & ")
        for _ in available
            print(io, " & IT & FE & CPU")
        end
        println(io, " \\\\")
        println(io, "\\midrule")
        println(io, "\\endfirsthead")
        println(io, "\\multicolumn{$(2 + 3*length(available))}{l}{\\textit{Continued from previous page}} \\\\")
        println(io, "\\midrule")
        print(io, "Problem & \$x_0\$")
        for m in available; print(io, " & IT & FE & CPU"); end
        println(io, " \\\\")
        println(io, "\\midrule")
        println(io, "\\endhead")
        println(io, "\\midrule")
        println(io, "\\multicolumn{$(2 + 3*length(available))}{r}{\\textit{Continued on next page}} \\\\")
        println(io, "\\endfoot")
        println(io, "\\bottomrule")
        println(io, "\\endlastfoot")

        for prob in problems
            x0s = sort(unique(filter(r -> r.problem == prob, df_dim).x0_label))
            for x0 in x0s
                print(io, "$prob & $x0")
                for m in available
                    rows = filter(r -> r.problem == prob && r.x0_label == x0 && r.method == m, df_dim)
                    if nrow(rows) == 1 && rows[1, :converged]
                        @printf(io, " & %d & %d & %.3f", rows[1,:iterations], rows[1,:f_evals], rows[1,:cpu_time])
                    elseif nrow(rows) == 1
                        print(io, " & --- & --- & ---")
                    else
                        print(io, " & & &")
                    end
                end
                println(io, " \\\\")
            end
        end
        println(io, "\\end{longtable}")
        println(io, "\\newpage")
        println(io, "")
    end

end
@tprintf(tee, "Saved: %s\n", table_b_tex)

# ═══════════════════════════════════════════════════════════════════════════════
# Table E: CS sweep summary (per method, aggregated over all configurations)
# ═══════════════════════════════════════════════════════════════════════════════

cs_csv = joinpath(JCODE_ROOT, "results", "signal_restore", "cs_sweep.csv")
if isfile(cs_csv)
    println(tee, "\n" * "=" ^ 75)
    println(tee, "Table E: Compressed Sensing Summary")
    println(tee, "=" ^ 75)

    cs_df = CSV.read(cs_csv, DataFrame)
    @tprintf(tee, "%-10s %6s %6s %7s %8s %8s %10s %12s\n",
             "Method", "Total", "Conv", "Rate%", "med_IT", "med_FE", "med_CPU", "med_MSE")
    println(tee, "-" ^ 75)

    table_e_rows = []
    for m in METHOD_ORDER
        sub = filter(r -> r.method == m, cs_df)
        nrow(sub) == 0 && continue
        conv = filter(r -> r.converged, sub)
        nt = nrow(sub); nc = nrow(conv)
        row = (method=m, total=nt, converged=nc,
               rate=round(100nc/nt; digits=1),
               med_IT=nc>0 ? median(conv.iterations) : NaN,
               med_FE=nc>0 ? median(conv.f_evals) : NaN,
               med_CPU=nc>0 ? median(conv.cpu_time) : NaN,
               med_MSE=nc>0 ? median(conv.mse) : NaN)
        push!(table_e_rows, row)
        @tprintf(tee, "%-10s %6d %6d %6.1f%% %8s %8s %10.2f %12.2e\n",
                 m, nt, nc, row.rate, format_median(row.med_IT),
                 format_median(row.med_FE), row.med_CPU, row.med_MSE)
    end

    table_e_tex = joinpath(TABLES_DIR, "table_E.tex")
    open(table_e_tex, "w") do io
        println(io, "% Table E: CS Summary (auto-generated by s75_tables.jl)")
        println(io, "\\begin{table}[ht]")
        println(io, "\\centering")
        println(io, "\\sisetup{exponent-mode=scientific, round-mode=places, round-precision=2}")
        println(io, "\\caption{Compressed sensing: median performance over all configurations and trials.}\\label{tab:cs}")
        println(io, "\\begin{tabular}{lrrrrrr}")
        println(io, "\\toprule")
        println(io, "Method & Total & Conv (\\%) & med IT & med FE & med CPU (s) & med MSE \\\\")
        println(io, "\\midrule")
        for r in table_e_rows
            @printf(io, "\\%s & %d & %.1f & %s & %s & %.2f & \\num{%.2e} \\\\\n",
                    r.method, r.total, r.rate, format_median(r.med_IT),
                    format_median(r.med_FE), r.med_CPU, r.med_MSE)
        end
        println(io, "\\bottomrule")
        println(io, "\\end{tabular}")
        println(io, "\\end{table}")
    end
    println(tee, "Saved: $table_e_tex")
else
    println(tee, "\nSkipping Table E: cs_sweep.csv not found")
end

# ═══════════════════════════════════════════════════════════════════════════════
# Table F: Logistic-regression summary
# ═══════════════════════════════════════════════════════════════════════════════

logreg_csv = joinpath(JCODE_ROOT, "results", "logreg", "logreg_results.csv")
if isfile(logreg_csv)
    println(tee, "\n" * "=" ^ 75)
    println(tee, "Table F: Logistic-Regression Summary")
    println(tee, "=" ^ 75)

    logreg_df = CSV.read(logreg_csv, DataFrame)
    table_f_rows = []
    for m in METHOD_ORDER
        sub = filter(r -> r.method == m, logreg_df)
        nrow(sub) == 0 && continue
        conv = filter(r -> r.converged, sub)
        nt = nrow(sub); nc = nrow(conv)
        push!(table_f_rows, (
            method=m,
            total=nt,
            rate=round(100nc/nt; digits=1),
            med_IT=nc>0 ? round(Int, median(conv.iterations)) : 0,
            med_FE=nc>0 ? round(Int, median(conv.f_evals)) : 0,
            med_CPU=nc>0 ? median(conv.cpu_time) : NaN,
            med_residual=nc>0 ? median(conv.residual) : NaN,
        ))
    end

    table_f_tex = joinpath(TABLES_DIR, "table_F.tex")
    open(table_f_tex, "w") do io
        println(io, "% Table F: Logistic-regression summary (auto-generated by s75_tables.jl)")
        println(io, "\\begin{table}[ht]")
        println(io, "\\centering")
        println(io, "\\sisetup{exponent-mode=scientific, round-mode=places, round-precision=2}")
        println(io, "\\caption{Logistic regression: median performance over all datasets and trials.}\\label{tab:logreg}")
        println(io, "\\begin{tabular}{lrrrrrr}")
        println(io, "\\toprule")
        println(io, "Method & Total & Conv (\\%) & med IT & med FE & med CPU (s) & med \$\\lVert G(x^*)\\rVert\$ \\\\")
        println(io, "\\midrule")
        for r in table_f_rows
            @printf(io, "\\%s & %d & %.1f & %d & %d & %.2f & \\num{%.2e} \\\\\n",
                    r.method, r.total, r.rate, r.med_IT, r.med_FE,
                    r.med_CPU, r.med_residual)
        end
        println(io, "\\bottomrule")
        println(io, "\\end{tabular}")
        println(io, "\\end{table}")
    end
    println(tee, "Saved: $table_f_tex")
else
    println(tee, "\nSkipping Table F: logreg_results.csv not found")
end

println(tee, "\n" * "=" ^ 75)
println(tee, "All tables generated.")
teardown_logging(tee, logpath)
